# Generated by Django 5.0.6 on 2024-07-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preentrega3app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='nombre',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
    ]
